[build]
  base = "frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://gideons-tech-suite-api.vercel.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
